### ISSUE TITLE
InfluxDB 0.9 : 404 not found.

### ISSUE THREAD

**Issue by tristanbes** [bernd/statsd-influxdb-backend#18]
Hi,

I can't have a `statsd` communicating with `Influxdb v0.9`.
All the settings I tried gives me `404 Not found` without giving me the endpoint for debug purposes.
Statsd and inxflux lives on the same server

My config:
```
    influxdb: {
        host: 'localhost',   // Tried influx-api.myhost.com behind SSL, and 127.0.0.1. 
        port: 8086, 
        version: 0.9,   
        ssl: false,         
        database: 'mydb', 
        username: 'myuser',  
        password: 'mypassword',  
        flush: {
          enable: true 
        },
        proxy: {
          enable: true,    
          suffix: 'raw',     
          flushInterval: 1000 
        },
        includeStatsdMetrics: false, 
        includeInfluxdbMetrics: false
    },
    graphitePort: 2003,
    graphiteHost: "localhost",
    port: 8125,
    legacyNamespace: false,
    debug: true,
    backends: [
        "./backends/graphite",
        "statsd-influxdb-backend"
    ]
}
```

My influx api is listening on port 8086. It's a fresh install of v0.9. 
**I have managed to send metrics via CURL to influx with the same credentials i use on this config**

**Comment by denen99** [comment]
@tristanbes i got this when my DB name was wrong.  I would suggest running tcpdump -A -s1500 host influxdb-host  and looking at the actual HTTP request.   Then try and curl that same request and see whats up.

**Comment by michaelmoss** [comment]
Hey, I ran into the same problem just now and was happy to find I wasn't the only one :). Looks like the problem is "npm install statsd-influxdb-backend" is pulling down version 0.5.0 which doesn't appear to have influx 0.9 support that master has. Compare: https://github.com/bernd/statsd-influxdb-backend/blob/v0.5.0/lib/influxdb.js and https://github.com/bernd/statsd-influxdb-backend/blob/master/lib/influxdb.js I'm not too familiar with node/npm so I myself am figuring out how to install statsd-influxdb-backend from master properly.

**Comment by michaelmoss** [comment]
Fix:
From the statsd directory: 
npm uninstall statsd-influxdb-backend
sudo npm install git+https://git@github.com/bernd/statsd-influxdb-backend.git

The above cmd defaults to master. It will say 0.5.0 because that's what package.json says in master, but it has the 0.9 API calls...

**Comment by bernd** [comment]
Sorry for slacking on this, I just published 0.6.0 to npmjs. So installing via npm should just work now.

**Comment by tristanbes** [comment]
Ok works, but I run straight to another problem https://github.com/bernd/statsd-influxdb-backend/issues/20

**Comment by pihomeserver** [comment]
Hi,
I'm using the 0.6.0 with statsd 0.7.2 and InfluxDB 0.9.4.2 and when statsd wants to flush data i got this message :

```
16 Oct 10:46:55 - [influxdb] (DEBUG) Sending 1 different points via HTTP
16 Oct 10:46:55 - [influxdb] (DEBUG) Payload size 0.09 KB
16 Oct 10:46:55 - [influxdb] HTTP Error: 404
```

My database exists, the user also
the following command works:

```
curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE mydb"
```

Any idea ?

**Comment by pihomeserver** [comment]
My fault. Checking the source code i found that the default version is 0.8 and it has to be set in the statsd configuration file ....

**Comment by bahmanrafatjoo** [comment]
I had the same problem with unexplained 404 errors and came across this thread. In case it helps others, here's a copy of my working config file with the version number set as suggested by @pihomeserver. Note the version setting is a number and not a string so it's 0.9 even though my influxdb version is '0.9.4'.

```
{
    influxdb: {
        host: '127.0.0.1',
        port: 8086,
        database: 'statsd',
        username: 'myuser',
        password: 'mypass',
        version: 0.9,
        flush: {
            enable: true
        },
        proxy: {
            enable: false,
            suffix: 'raw',
            flushInterval: 1000
        },
        includeStatsdMetrics: true,
        includeInfluxdbMetrics: true,
    },
    port: 8125,
    backends: ['./backends/console', 'statsd-influxdb-backend'],
    debug: true,
    legacyNamespace: false
}
```

**Comment by oriste** [comment]
Linux 4.1.15-v7+ #830 SMP Tue Dec 15 17:02:45 GMT 2015 armv7l GNU/Linux
Node v4.2.4
NPM 2.14.12
Influxdb v0.9.6
Statsd 0.7.2 (even though NPM reports statsd@0.7.1)

With the config.js file above that I copied from @bahmanrafatjoo, I get 

> 10 Jan 23:49:48 - reading config file: /opt/statsd/config.js
> 10 Jan 23:49:48 - server is up
> 10 Jan 23:49:48 - DEBUG: Loading backend: statsd-influxdb-backend
> 10 Jan 23:49:58 - [influxdb] TypeError: Object #<EventEmitter> has no method 'hrtime'
> 10 Jan 23:50:08 - [influxdb] TypeError: Object #<EventEmitter> has no method 'hrtime'
> 10 Jan 23:50:18 - [influxdb] TypeError: Object #<EventEmitter> has no method 'hrtime'
> 10 Jan 23:50:28 - [influxdb] TypeError: Object #<EventEmitter> has no method 'hrtime'
> ...and so on, forever.

No data flows from statsd to influxdb.

I installed the backend as follows:

> $ sudo npm install statsd-influxdb-backend -d
> npm info it worked if it ends with ok
> npm info using npm@2.14.12
> npm info using node@v4.2.4
> npm WARN package.json statsd@0.7.1 No license field.
> npm info addNameTag [ 'statsd-influxdb-backend', 'latest' ]
> npm info attempt registry request try #1 at 3:20:23 PM
> npm http request GET https://registry.npmjs.org/statsd-influxdb-backend
> npm http 200 https://registry.npmjs.org/statsd-influxdb-backend
> npm info retry fetch attempt 1 at 3:20:24 PM
> npm info attempt registry request try #1 at 3:20:24 PM
> npm http fetch GET https://registry.npmjs.org/statsd-influxdb-backend/-/statsd-influxdb-backend-0.6.0.tgz
> npm http fetch 200 https://registry.npmjs.org/statsd-influxdb-backend/-/statsd-influxdb-backend-0.6.0.tgz
> npm info install statsd-influxdb-backend@0.6.0 into /opt/statsd
> npm info installOne statsd-influxdb-backend@0.6.0
> npm info preinstall statsd-influxdb-backend@0.6.0
> npm info build /opt/statsd/node_modules/statsd-influxdb-backend
> npm info linkStuff statsd-influxdb-backend@0.6.0
> npm info install statsd-influxdb-backend@0.6.0
> npm info postinstall statsd-influxdb-backend@0.6.0
> statsd-influxdb-backend@0.6.0 node_modules/statsd-influxdb-backend
> npm info ok 
> $

I'm pretty new to all this. Does anyone know a solution for it?

**Comment by codervarun** [comment]
I am using influxdb 0.12 version and using below setting 
{
  influxdb: {
    host: '127.0.0.1', // InfluxDB host (default 127.0.0.1)
    port: 8086, // InfluxDB port (default 8086)
    version : 0.12,
    database: 'demo',  // InfluxDB db instance (required)
    //username: 'root', // InfluxDB db username (required)
   // password: 'root', // InfluxDB db password (required)
    flush: {
      enable: true // enable regular flush strategy (default true)
    },
    proxy: {
      enable: false, // enable the proxy strategy (default false)
      suffix: 'raw', // metric name suffix (default 'raw')
      flushInterval: 1000
    }
  },
  port: 8125, // statsD port
  backends: ['./backends/console', 'statsd-influxdb-backend'],
  debug: true
  //legacyNamespace: false
}

and still getting [influxdb] HTTP Error: 404 

What could be problem here ?

Thanks
Varun

**Comment by pihomeserver** [comment]
@codervarun are you sure that your influxdb API is available (try without statd) ?

**Comment by codervarun** [comment]
@pihomeserver : I am able to do localhost:8083 and can see influxdb in browser and also kapacitor is able to get alerts also from influxdb. 
But not sure why this above case is not working ,is it influxdb db version 0.12 and statsd is not compatible ?

**Comment by pihomeserver** [comment]
@codervarun sorry no idea for 0.12 as i switched to telegraf to collect my data (it includes a statsd like collector)

**Comment by codervarun** [comment]
@pihomeserver : Anyway thanks :)

**Comment by zhiwzhao** [comment]
this can be closed as i already make statsd support influxdb  v0.12

**Comment by sagarshetty** [comment]
I am still getting [influxdb] HTTP Error: 404 on windows. I tried re installing everything from scratch couple of times.

StatsD error: [influxdb] HTTP Error: 404 
InfluxDB error: [httpd] 2016/05/05 15:29:50 127.0.0.1 - root [05/May/2016:15:29:50 -0700] POST /write?p=%5BREDACTED%5D&u=root HTTP/1.
1 400 33 - - e1433f85-1310-11e6-8001-000000000000 0

I have to set the version = 0.9 even though I have the latest influxDB v0.12 installed as it does not work when I set version = 0.12. 

{
    influxdb: {
        host: '127.0.0.1',
        port: 8086,
        database: 'demo',
        username: 'root',
        password: 'root',
        version: 0.9,
        flush: {
            enable: true
        },
        proxy: {
            enable: false,
            suffix: 'raw',
            flushInterval: 1000
        },
        includeStatsdMetrics: true,
        includeInfluxdbMetrics: true,
    },
    port: 8125,
    backends: ['./backends/console', 'statsd-influxdb-backend'],
    debug: true,
    legacyNamespace: false
}

**Comment by sagarshetty** [comment]
@zhiwzhao :+1: Thanks, I found your solution.

https://github.com/bernd/statsd-influxdb-backend/pull/35/commits/dee837d9c8780bfe7572061009c6b9ebc8a214d5

**Comment by gcyre** [comment]
I'm having the same issue with influxdb version 1.0, I've tried setting "version: 1.0," but still receive the 404 error. 

any help would be appriciated

**Comment by gcyre** [comment]
my config and error:

{
  influxdb: {
    host: '127.0.0.1',
    port: 8086,
    database: 'demo',
    username: 'demo',
    password: 'demo123',
    version: 1.0,
    flush: {
      enable: true
    },
    proxy: {
      enable: false,
      suffix: 'raw',
      flushInterval: 1000
    }
  },
  port: 8125,
  backends: ['./backends/console', 'statsd-influxdb-backend'],
  percentThreshold: [ 50, 90, 99, 99.9, 99.99 ],
  debug: true,
  legacyNamespace: false
}

21 Sep 19:33:10 - [influxdb](DEBUG) Sending 1 different points via HTTP
21 Sep 19:33:10 - [influxdb](DEBUG) Payload size 0.09 KB
21 Sep 19:33:10 - [influxdb] HTTP Error: 400
