### ISSUE TITLE
Getting [influxdb] HTTP Error: 404 - with influxdb 0.12 

### ISSUE THREAD

**Issue by codervarun** [bernd/statsd-influxdb-backend#34]
I am using influxdb 0.12 version and using below setting 
{
influxdb: {
host: '127.0.0.1', // InfluxDB host (default 127.0.0.1)
port: 8086, // InfluxDB port (default 8086)
version : 0.12,
database: 'demo', // InfluxDB db instance (required)
//username: 'root', // InfluxDB db username (required)
// password: 'root', // InfluxDB db password (required)
flush: {
enable: true // enable regular flush strategy (default true)
},
proxy: {
enable: false, // enable the proxy strategy (default false)
suffix: 'raw', // metric name suffix (default 'raw')
flushInterval: 1000
}
},
port: 8125, // statsD port
backends: ['./backends/console', 'statsd-influxdb-backend'],
debug: true
//legacyNamespace: false
}

and still getting [influxdb] HTTP Error: 404

What could be problem here ?

Thanks
Varun

**Comment by Azulinho** [comment]
same issue here

**Comment by zhiwzhao** [comment]
i have upgrade it to support influxdb 0.11 &0.12. so far work fine.
the root cause you get error is that currently the backend is use json protocal, i change to line protocal.
at the same time, the RP attribute is added in config.
code will be committed later.

**Comment by codervarun** [comment]
@zhiwzhao : Cool , when are you going to checkin this patch to this repository . Eagerly waiting for it :)

**Comment by zhiwzhao** [comment]
@codervarun ,i am already commit to the github. you can have a try.
https://github.com/bernd/statsd-influxdb-backend/pull/35/commits/dee837d9c8780bfe7572061009c6b9ebc8a214d5

**Comment by predrag-rakic** [comment]
@zhiwzhao  I'm having the same issue. Can't pull your fix?

**Comment by zhiwzhao** [comment]
@predrag-rakic  you can download from https://github.com/zhiwzhao/statsd-influxdb-backend

**Comment by codervarun** [comment]
@zhiwzhao I tried with influxdb 0.13 but i am still getting Http 404 error. Does it work with influxdb 0.13 version also as 0.13 also uses line protocol.
I installed module using-- npm install git+https://github.com/zhiwzhao/statsd-influxdb-backend.git

**Comment by Azulinho** [comment]
as a workaround I simply deployed a statsd endpoint on the same nodes as influxdb

**Comment by mchesler** [comment]
@codervarun Try `npm install git+https://github.com/mchesler/statsd-influxdb-backend.git` (PR #36).  It's working well for me against InfluxDB v0.13.  I was hitting the same 404 error you were getting.

**Comment by abhineet-mishra** [comment]
Thanks @mchesler. I was hitting the same 404 error. Your github code solved the issue.

**Comment by codervarun** [comment]
Worked using mchesler code
