### ISSUE TITLE
Why are StatsD stats counters disabled?

### ISSUE THREAD

**Issue by gnjack** [bernd/statsd-influxdb-backend#6]
The counter metics generated by StatsD itself are specifically filtered out of the data sent to InfluxDB. Is there a reason for this? At the very least it feels like this filter should be optional.

```
  for (key in counters) {
    /* Do not include statsd counters. */
    if (key.match(/^statsd\./)) { continue; }
```
https://github.com/bernd/statsd-influxdb-backend/blob/master/lib/influxdb.js#L137

**Comment by gnjack** [comment]
Support for sending the `statsd_metrics` data from StatsD the backend interface and generating some basic InfluxDB backend metrics would be a great feature, as seen in the [Graphite backend](https://github.com/etsy/statsd/blob/master/backends/graphite.js). I may consider creating a PR for this.

**Comment by kureikain** [comment]
I think we should make this into a configurable option. However, the reason behinds it prolly is to reduce load for InfluxDB I think.

**Comment by bernd** [comment]
I added a `includeStatsdMetrics` option to the configuration. (default false)

See: https://github.com/bernd/statsd-influxdb-backend#configuration

Hope that helps.

**Comment by gnjack** [comment]
The `if (key.match(/^statsd\./))` logic does not work if the `prefixStats` config parameter is changed from `statsd` to something that does not begin with `statsd`

**Comment by bernd** [comment]
Good catch @gnjack, thanks! Commit cce20b6 should fix that.
